// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EatGhost(arg1:string):Promise<void>;

export function ResetGhosts():Promise<void>;

export function ScareGhosts():Promise<void>;

export function SetPlayerPosition(arg1:number,arg2:number):Promise<void>;
