// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EatGhost(arg1) {
  return window['go']['main']['GameEngine']['EatGhost'](arg1);
}

export function ResetGhosts() {
  return window['go']['main']['GameEngine']['ResetGhosts']();
}

export function ScareGhosts() {
  return window['go']['main']['GameEngine']['ScareGhosts']();
}

export function SetPlayerPosition(arg1, arg2) {
  return window['go']['main']['GameEngine']['SetPlayerPosition'](arg1, arg2);
}
