// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPellets():Promise<Array<any>>;

export function GetPlayerPosition():Promise<main.PlayerUpdate>;

export function GetState():Promise<main.GameState>;

export function MovePlayer(arg1:string):Promise<boolean>;

export function ResetGhosts():Promise<void>;
